### PR TITLE
Devfund increase

### PR DESCRIPTION
**Pull request by atdev1**
Solving task # 22

- Dev reward address update from 53NTdWeAxEfVjXufpBqU2YKopyZYmN9P1V to CPhPudPYNC8uXZPCHovyTyY98Q6fJzjJLm
- Dev fund rewards emission increase from 0.5 CRDS to 1 CRDS per block
- Protocol Bump from 70003 to 70004 (mandatory update)

### CODE REVIEW

**Comment by atdev1** [comment]
Good, I will apply those changes.  What chain height are you aiming for this new fork?

**Comment by mdrankin** [comment]
> Good, I will apply those changes. What chain height are you aiming for this new fork?

Block 550,000 should give us plenty of time.

**Comment by atdev1** [comment]
Just found an issue with the commit, cannot be merged yet.  Will update soon.

**Comment by atdev1** [comment]
New pull requested opened with final changes

**Pull request closed without merging**
